from __future__ import annotations

import os
import requests
from typing import TypedDict, List, Optional
from rag_app.config.settings import TAVILY_API_KEY

class TavilySource(TypedDict):
    url: str
    content: str
    title: Optional[str]

class TavilyResponse(TypedDict):
    answer: str
    sources: List[str]  # List of URLs

def query_tavily(question: str, timeout: float = 8.0) -> TavilyResponse:
    """
    Queries the Tavily API for a given question.
    Returns an answer and a list of source URLs.
    """
    if not TAVILY_API_KEY:
        return {
            "answer": "Error: TAVILY_API_KEY not configured.",
            "sources": []
        }

    url = "https://api.tavily.com/search"
    payload = {
        "api_key": TAVILY_API_KEY,
        "query": question,
        "search_depth": "basic",
        "include_answer": True,
        "include_images": False,
        "include_raw_content": False,
        "max_results": 3,
    }

    try:
        response = requests.post(url, json=payload, timeout=timeout)
        response.raise_for_status()
        data = response.json()
        
        answer = data.get("answer", "No answer generated by Tavily.")
        # Extract URLs from results
        results = data.get("results", [])
        sources = [r.get("url") for r in results if r.get("url")]
        
        return {
            "answer": answer,
            "sources": sources
        }

    except Exception as e:
        return {
            "answer": f"Error querying Tavily: {str(e)}",
            "sources": []
        }
